[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoints={sepolia="https://eth-sepolia.g.alchemy.com/v2/r1-e0aQwppftItL-fKeP1", arb-sepolia="https://arb-sepolia.g.alchemy.com/v2/r1-e0aQwppftItL-fKeP1"}
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
     '@ccip/=lib/ccip/',
     '@chainlink-local/=lib/chainlink-local/'
]